# Generated by Django 5.1 on 2024-08-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
